Lesson7/WebApplication3/Models/Catalog.cs
namespace WebApplication3.Models
{
    public class Catalog
    {
        public List<Category> GetCategories { get; set; } = new();
    }

    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Lesson7/WebApplication3/Models/ErrorViewModel.cs
namespace WebApplication3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lesson7/WebApplication3/Models/ProductsCatalog.cs
using System.Collections.Concurrent;
using WebApplication3;
    
namespace WebApplication3.Models
{
    public class ProductModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }

        public FormUrlEncodedContent ToFormData()
        {
            return new FormUrlEncodedContent(new[]
            {
            new KeyValuePair<string, string>(nameof(Name), Name),
            new KeyValuePair<string, string>(nameof(Id), Id.ToString()),
            new KeyValuePair<string, string>(nameof(Description), Description),
            new KeyValuePair<string, string>(nameof(Type), Type)
        });
        }
    }

}

Lesson7/WebApplication3/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication3.Models;


namespace WebApplication3.Controllers
{
    public class CatalogController  : Controller
    {
        private static Catalog _catalog = new();

        [HttpGet]
        public IActionResult Categories()
        {
            return View(_catalog);
        }

        [HttpPost]
        public IActionResult Categories(Category model)
        {
            _catalog.GetCategories.Add(model);
            return View(_catalog);
         

        }
    }
}

Lesson7/WebApplication3/Controllers/DeleteProductsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication3.Models;
using WebApplication3.Services;
using WebApplication3.Interfaces;
using Microsoft.Extensions.Options;

namespace WebApplication3.Controllers
{
    public class DeleteProductsController : Controller
    {
        private TreadSafeCollection _collection = new TreadSafeCollection();
        private ProductCatalogService _IproductService = new ProductCatalogService();
        private EmailService _emailService = new EmailService();

        public DeleteProductsController(IOptions<EmailService> emailService, IOptions<ProductCatalogService> productCatalogService, IOptions<TreadSafeCollection> options)
        {
            _emailService = emailService.Value;
            _IproductService = productCatalogService.Value;
            _collection = options.Value;
        }

        [HttpGet]
        public IActionResult DeleteProducts()
        {
            return View(_collection.GetAll());
        }

        [HttpPost]
        public IActionResult DeleteProducts([FromForm] ProductModel exemp)
        {
            _collection.Remove(exemp);
            _IproductService.ToConverter();
            _emailService.SendEmail("Dimon1998daf@mail.ru", "C магазина был убран товар", "Убран товар с id " + exemp.Id + ", наименованием " + exemp.Name + ", описанием " + exemp.Description + ", типом " + exemp.Type, "Дмитрия ", "Яковлева");
            return View(_collection.GetAll());
        }
    }
}

Lesson7/WebApplication3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["Footer"] = "(c) DimasX";
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lesson7/WebApplication3/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication3.Models;
using WebApplication3.Services;
using WebApplication3.Interfaces;
using Microsoft.Extensions.Options;
using OpenXmlPowerTools;

namespace WebApplication3.Controllers
{
    public class ProductController : Controller
    {

        private TreadSafeCollection _collection = new TreadSafeCollection();
        private static EmailService _emailService = new EmailService();
        private ProductCatalogService _IproductService = new ProductCatalogService();
        private CancellationTokenSource cts = new CancellationTokenSource();
       
        
        public ProductController(IOptions<EmailService> emailService, IOptions<ProductCatalogService> productCatalogService, IOptions<TreadSafeCollection> options)
        {
            _emailService = emailService.Value;
            _IproductService = productCatalogService.Value;
            _collection = options.Value;
            
        }

        [HttpGet]
        public IActionResult Products()
        {
          return View(_collection.GetAll());
        }

        [HttpPost]
        public IActionResult Products([FromForm]ProductModel exemp)
        {
            IsWorkedBackgroundService service = new IsWorkedBackgroundService(_emailService);
            var ct = cts.Token;
            if (!(ct.IsCancellationRequested))
            {
                _collection.Add(exemp,ct);
                _IproductService.ToConverter();
                _emailService.SendEmail("Dimon1998daf@mail.ru", "В магазин был добавлен новый товар", "Добавлен товар с id " + exemp.Id + ", наименованием " + exemp.Name + ", описанием " + exemp.Description + ", типом " + exemp.Type,  "Дмитрия ", "Яковлева");
            }
            return View(_collection.GetAll());
        }
       
    }
}

Lesson7/WebApplication3/Controllers/ProductListController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebApplication3.Interfaces;
using WebApplication3.Models;
using WebApplication3.Services;

namespace WebApplication3.Controllers
{
    public class ProductListController : Controller
    {
        private TreadSafeCollection _collection = new TreadSafeCollection();

        public ProductListController(IOptions<TreadSafeCollection> options)
        {
            _collection = options.Value;
        }

        public IActionResult ProductList()
        {
            return View(_collection.GetAll());
        }

    }
}

Lesson7/WebApplication3/Views/Product/Products.cshtml
@model IReadOnlyCollection<ProductModel>

@{
    ViewData["Title"] = "Добавление продуктов";
}


<form method="post">
    Id: <input type="text" name="id" required />
    <br/>
    Имя: <input type="text" name="name" />
    <br/>
    Описание: <input type="text" name="description" />
    <br/>
    Тип: <input type="text" name="type" />
    <br/>
    <input type="submit" name="submit" value="Создать" />
</form>

Lesson7/WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Categories">Категории</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Products">Добавление продукта</a>
                        </li>
                        <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="ProductList" asp-action="ProductList">Список продуктов</a>
                         </li>
                          <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="DeleteProducts" asp-action="DeleteProducts">Удаление продуктов</a>
                         </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
          @*подставляется код из html*@  
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - @ViewData["Footer"] - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>